### ISSUE TITLE
Add some tests

### ISSUE THREAD

**Issue by DyspC** [DyspC/LyricsPrimer#1]
This is an old decompiled / imported / tweaked multiple times project with lots of complex per-character rules that make it hard to find regressions at development time.  

That being said it lacks tests: 
- Some that run on excerpt constants in the code
- Some that run on text files and apply given methods 
For example: 
 `src/test/resources/out/file1.methodX.methodY.sample` would trigger a test asserting that its content is the same as what `methodY(methodX({content of src/test/resources/in/file1.sample})` outputs (don't do reflection there are 3 buttons)

**Comment by DyspC** [comment]
Note to myself

- [ ] Create CONTRIBUTING.md
- [ ] Write README.md wtf is that thing supposed to do

**Comment by NyorJa** [comment]
Can I give this a try? Thanks

**Comment by DyspC** [comment]
Yeah sure, 

If you want me to provide you with some before/after test data don't hesitate and ask me

**Comment by NyorJa** [comment]
that would be great!thanks again

**Comment by DyspC** [comment]
Hi, I've put some test files on the 'testing' branch
